const fileStructure={
   id:"1",
   name:"SANDBOX",
   isFolder:true,
   childFolders:[
    {
        id:"2",
        name:".codesandbox",
        isFolder:true,
        childFolders:[
            {
                id:"3",
                name:"app.jsx",
                isFolder:false
            },
            {
                id:"4",
                name:"text.jsx",
                isFolder:false
            },
            {
                id:"5",
                name:"another.jsx",
                isFolder:false
            }
        ]
    },
    {
        id:"6",
        name:".devcontainer",
        isFolder:true,
        childFolders:[
            {
                id:"7",
                name:"components",
                isFolder:true,
                childFolders:[
                    {
                        id:"8",
                        name:"cmp.jsx",
                        isFolder:false
                    },
                    {
                        id:"9",
                        name:"head.jsx",
                        isFolder:false
                    },{
                        id:"10",
                        name:"header.jsx",
                        isFolder:false
                    }
                ]
            }
        ]
    }
   ]
}


export default fileStructure;